# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- script: echo mymaven pipeline
  displayName: 'Run a one-line script'
- script: mvn clean install
  displayName: 'build with maven'
- script: java -jar target/maventest-1.0.jar
  displayName: 'running jar'